import { FormEvent } from "react";
import { useForm } from "@inertiajs/react";
import Button from "@/components/Button/Button";

export type BannerFormData = { title: string; description: string; button_label: string; button_url: string; image: File | null; sort_order: number; is_active: boolean };
export default function BannerForm({ initialData, submit, submitLabel }: { initialData?: Partial<BannerFormData> & { imageUrl?: string | null }; submit: (form: ReturnType<typeof useForm<BannerFormData>>) => void; submitLabel: string }) {
    const form = useForm<BannerFormData>({ title: initialData?.title ?? "", description: initialData?.description ?? "", button_label: initialData?.button_label ?? "", button_url: initialData?.button_url ?? "", image: null, sort_order: initialData?.sort_order ?? 0, is_active: initialData?.is_active ?? true });
    return <form onSubmit={(e: FormEvent) => { e.preventDefault(); submit(form); }} className="space-y-5 rounded-2xl bg-white p-6 shadow-sm"><label className="block text-sm font-medium">Title<input value={form.data.title} onChange={e => form.setData('title', e.target.value)} className="mt-2 w-full rounded-xl border p-2" />{form.errors.title && <span className="text-xs text-red-600">{form.errors.title}</span>}</label><label className="block text-sm font-medium">Description<textarea value={form.data.description} onChange={e => form.setData('description', e.target.value)} className="mt-2 min-h-24 w-full rounded-xl border p-2" /></label><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">Button label<input value={form.data.button_label} onChange={e => form.setData('button_label', e.target.value)} className="mt-2 w-full rounded-xl border p-2" /></label><label className="text-sm font-medium">Button URL<input value={form.data.button_url} onChange={e => form.setData('button_url', e.target.value)} className="mt-2 w-full rounded-xl border p-2" /></label><label className="text-sm font-medium">Order<input type="number" min="0" value={form.data.sort_order} onChange={e => form.setData('sort_order', Number(e.target.value))} className="mt-2 w-full rounded-xl border p-2" /></label></div><label className="block text-sm font-medium">Banner image{initialData?.imageUrl && <img src={initialData.imageUrl} alt="Current banner" className="my-2 h-24 w-40 rounded-lg object-cover" />}<input type="file" accept="image/*" onChange={e => form.setData('image', e.target.files?.[0] ?? null)} className="mt-2 block w-full" />{form.errors.image && <span className="text-xs text-red-600">{form.errors.image}</span>}</label><label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" checked={form.data.is_active} onChange={e => form.setData('is_active', e.target.checked)} /> Active</label><Button type="submit" disabled={form.processing}>{submitLabel}</Button></form>;
}
