import { Link, useForm } from "@inertiajs/react";
import AdminLayout from "@/layouts/AdminLayout";
import Button from "@/components/Button/Button";

type Item = { id: number; product_name: string; quantity: number; unit_price: number; line_total: number };
type Order = { order_number: string; customer_name: string; customer_email: string; phone: string; address: string; city: string; postal_code: string; status: string; payment_status: string; subtotal: number; shipping_cost: number; grand_total: number; items: Item[] };
type Props = { order: Order; statuses: string[]; paymentStatuses: string[] };

export default function Show({ order, statuses, paymentStatuses }: Props) {
    const form = useForm({ status: order.status, payment_status: order.payment_status });
    return <AdminLayout><div className="mb-6 flex items-center justify-between"><div><p className="text-sm uppercase tracking-widest text-stone-500">Order</p><h1 className="text-3xl font-bold">{order.order_number}</h1></div><Link href={route("admin.orders.index")}><Button variant="outline">Back</Button></Link></div><div className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]"><section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Items</h2><div className="mt-4 space-y-3">{order.items.map((item) => <div key={item.id} className="flex justify-between border-b border-stone-100 pb-3"><div><p className="font-medium">{item.product_name}</p><p className="text-sm text-stone-500">Qty: {item.quantity}</p></div><p>Rp {Number(item.line_total).toLocaleString("id-ID")}</p></div>)}</div><div className="mt-6 space-y-2 text-sm"><p className="flex justify-between"><span>Subtotal</span><span>Rp {Number(order.subtotal).toLocaleString("id-ID")}</span></p><p className="flex justify-between"><span>Shipping</span><span>Rp {Number(order.shipping_cost).toLocaleString("id-ID")}</span></p><p className="flex justify-between border-t border-stone-200 pt-2 text-base font-bold"><span>Total</span><span>Rp {Number(order.grand_total).toLocaleString("id-ID")}</span></p></div></section><aside className="space-y-6"><section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Customer</h2><div className="mt-4 space-y-2 text-sm text-stone-600"><p>{order.customer_name}</p><p>{order.customer_email}</p><p>{order.phone}</p><p>{order.address}, {order.city}, {order.postal_code}</p></div></section><form onSubmit={(event) => { event.preventDefault(); form.put(route("admin.orders.update", order.order_number)); }} className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Status</h2><label className="mt-4 block text-sm font-medium">Order status<select value={form.data.status} onChange={(event) => form.setData("status", event.target.value)} className="mt-2 w-full rounded-xl border border-stone-300 px-3 py-2">{statuses.map((status) => <option key={status}>{status}</option>)}</select></label><label className="mt-4 block text-sm font-medium">Payment status<select value={form.data.payment_status} onChange={(event) => form.setData("payment_status", event.target.value)} className="mt-2 w-full rounded-xl border border-stone-300 px-3 py-2">{paymentStatuses.map((status) => <option key={status}>{status}</option>)}</select></label><Button type="submit" className="mt-5" disabled={form.processing}>Save status</Button></form></aside></div></AdminLayout>;
}
